# 先在 NFS 上建目录：
#   mkdir -p /data/nfs/shared/nexus/postgres /data/nfs/shared/nexus/data
#   chown -R 200:200 /data/nfs/shared/nexus/data      # nexus3 uid

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nexus-data
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nexus-nfs
  nfs:
    server: 172.16.10.129
    path: /data/nfs/shared/nexus/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nexus-data
  namespace: nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-nexus-data
  storageClassName: nexus-nfs
