# HTTP 80 + HTTPS 443
# TLS Secret 须与 Gateway 同命名空间：default/star.obsbot.lan（type kubernetes.io/tls）
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: default
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: star.obsbot.lan
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: All
